### ISSUE TITLE
Are the copyright statements correct?

### ISSUE THREAD

**Issue by no-reply** [ucsdlib/otm-specs#1]
`overrideCopyright: "<p class='copyright'>This document is licensed under a <a class='subfoot' href='https://creativecommons.org/licenses/by/4.0/' rel='license'>Creative Commons Attribution 4.0 License</a>.</p>",`

Are these CC 4.0?

**Comment by bbranan** [comment]
Good question, that line was a copy-paste from the OCFL spec.

**Comment by no-reply** [comment]
cc: @SibylSchaefer

**Comment by bbranan** [comment]
Licenses are now consistently CC Attribution v4.0
