### ISSUE TITLE
Gateway Spec comments/suggestions

### ISSUE THREAD

**Issue by bbranan** [ucsdlib/otm-specs#14]
### Intro
* ~~The “Gateway Overview” section is empty, should it be removed?~~
* ~~Is there a need for the “Gateway API” section header? (The other specs don't have a similar top-level section.)~~

### Deposit Object
* `x-otm-preservation-provider` - do we want to embed the "otm" name in a component of the Gateway API? Perhaps `x-gateway-preservation-provider` instead?

### Get Object Audit
* Missing description of what this task does
* Is there meant to be content in the example? If not, consider removing.

### Destroy Object
* ~~Should this be “Delete Object”~~
* ~~Missing description of what this task does~~

### Initiate Restore
* ~~Why `/{object-id}?restore` rather than `/{object-id}/restore`?~~
* ~~Shouldn’t there be a way to specify the restore of a specific version?~~
* ~~202 response code needs additional descriptive text~~
* ~~Why send a 409 (error) response code if the restore is in process? If this were a 202 instead (if it was a new request or a duplicate), then this endpoint would seem appropriate to poll to determine if the had yet completed (200 if so, 202 if not). A 409 would seem to discourage this practice.~~

### Retrieve Object
* ~~Missing description of what this task does~~
* ~~412 response code needs additional descriptive text~~
* ~~Is this the right endpoint to poll to determine if a requested restore is now available to retrieve? If so, a 403 (Forbidden) error is an odd code to get back in the event that an object is being restored but isn't ready yet.~~ 

### Transfer File
* ~~Missing example~~

**Comment by no-reply** [comment]
I've crossed out the issues that have already been addressed.

I can't recall if we came to a conclusion about `x-otm-*`. Let's discuss.

The other issue is represented by #69.

**Comment by no-reply** [comment]
we decided to keep `x-otm`
