### ISSUE TITLE
Define "minimal versioning capability"

### ISSUE THREAD

**Issue by diamondap** [ucsdlib/otm-specs#15]
In the README, the last bullet point under https://ucsdlib.github.io/otm-specs/#ddp says "The DDP must support at least minimal versioning capability." You should define what that means. After reading through the bridge and gateway specs, it seems to mean the DDP can ingest and maintain multiple versions of the same object or filegroup, and can restore or delete any of those versions on request.

**Comment by bbranan** [comment]
@diamondap how does this look? https://github.com/ucsdlib/otm-specs/pull/27
