### ISSUE TITLE
Audit Events: Review comments

### ISSUE THREAD

**Issue by diamondap** [ucsdlib/otm-specs#19]
Please review comments and typo fixes in 
[AuditEvents.pdf](https://github.com/ucsdlib/otm-specs/files/3871194/AuditEvents.pdf)

**Comment by mikejritter** [comment]
@diamondap you can see the changes made based on your suggestions in #32. We opted not to add any DDP identifier on the ingest event for now to try and keep the event as simple as possible, as the specs only talk about using the `filegroup-id` which is created from the OTM Gateway.

**Comment by diamondap** [comment]
That's fine. I suppose people outside the DDP wouldn't care about the DDP's internal identifier. And if there were ever a case where someone needed to know, the DDP should be able to map the filegroup-id to it's own internal identifier. If there are no other issues, go ahead and close this.

**Comment by bbranan** [comment]
Resolved in https://github.com/ucsdlib/otm-specs/pull/32
