### ISSUE TITLE
Draft appropriate "Status of this Document" text

### ISSUE THREAD

**Issue by no-reply** [ucsdlib/otm-specs#2]
The default StoD text isn't really applicable. Replace it with something more appropriate.

**Comment by SibylSchaefer** [comment]
This document is a draft of a specification, created as part of the One-to-Many grant, funded by the Andrew W. Mellon Foundation. 

Note: we will likely want to remove "draft" after the Advisory Board Review.

**Comment by bbranan** [comment]
Updated text applied to all spec/appendix docs
