### ISSUE TITLE
Spec typos and minor edits (review by Kathryn Michaelis)

### ISSUE THREAD

**Issue by bbranan** [ucsdlib/otm-specs#25]
Kathryn Michaelis provided the following suggested changes:

[OTM_Appendix_Audit_Events.docx](https://github.com/ucsdlib/otm-specs/files/3887662/OTM_Appendix_Audit_Events.docx)
[OTM_Appendix_Preservation_Workflow.docx](https://github.com/ucsdlib/otm-specs/files/3887663/OTM_Appendix_Preservation_Workflow.docx)
[OTM_Bridge_API_Spec.docx](https://github.com/ucsdlib/otm-specs/files/3887664/OTM_Bridge_API_Spec.docx)

**Comment by mikejritter** [comment]
Incorporated preservation workflow suggestions into #24
