### ISSUE TITLE
Minor wording suggestion: "transitioned"?

### ISSUE THREAD

**Issue by awoods** [ucsdlib/otm-specs#28]
Minor wording suggestion:
Change `transitioned` to `replicated`? `copied`?

https://github.com/ucsdlib/otm-specs/blob/fc0c8cd5e41c214ef7284ec032112d5aefd315c6/preservation-workflow.html#L47

**Comment by mikejritter** [comment]
Trying out `copied` for now; incorporated into #24

**Comment by awoods** [comment]
Resolved with: https://github.com/ucsdlib/otm-specs/pull/24
