### ISSUE TITLE
Minor editorial suggestion: separate paragraph

### ISSUE THREAD

**Issue by awoods** [ucsdlib/otm-specs#29]
I believe the final sentence would make even more sense, if it were separated into its own paragraph:
```
Additional notes are provided for the minimum required steps for implementation in Chronopolis.
```

https://github.com/ucsdlib/otm-specs/blob/fc0c8cd5e41c214ef7284ec032112d5aefd315c6/preservation-workflow.html#L64-L65

**Comment by mikejritter** [comment]
Incorporated into #24
