### ISSUE TITLE
Preservation workflow text 

### ISSUE THREAD

**Issue by SibylSchaefer** [ucsdlib/otm-specs#77]
"The primary purpose of the systems and integrations described by the OTM Specifications is to support the deposit and recovery of content. Content is to be considered recoverable only after it has completed a successful deposit. **Objects that have been successfully deposited from a Repository into a DDP are intended to be recoverable using only the data that resides in the DDP, even if all other OTM system components have failed.** There are no guarantees of recoverability if content has not first completed a successful deposit."

Bolded part is unclear. Also introduces the notion of Objects for the first time in a linear reading of the Spec (README, then Workflow page) so maybe should be linked to where objects are described?

**Comment by no-reply** [comment]
> The primary purpose of the systems and integrations described by the OTM Specifications is to support the deposit and recovery of content. Content is to be considered recoverable only after it has completed a successful deposit. Content that has been deposited from a Repository into a DDP is intended to be recoverable even if all other OTM system components have failed. There are no guarantees of recoverability if content has not fully completed a deposit.

**Comment by SibylSchaefer** [comment]
Change made.
